### PR TITLE
Do not crash application on invalid `Origin` value

### LINKED ISSUE #44: Invalid `Origin` Header crashes Application
We experience some Issues in our Application:

```
exception 'Zend\Http\Header\Exception\InvalidArgumentException' with message 'Invalid header value for Origin key: "Origin"' in ./vendor/zendframework/zend-http/src/Header/Origin.php:36
Stack trace:
#0 ./vendor/zendframework/zend-http/src/Headers.php(448): Zend\Http\Header\Origin::fromString('Origin: file:')
#1 ./vendor/zendframework/zend-http/src/Headers.php(287): Zend\Http\Headers->lazyLoadHeader(11)
#2 ./vendor/zfr/zfr-cors/src/ZfrCors/Service/CorsService.php(65): Zend\Http\Headers->get('Origin')
#3 ./vendor/zfr/zfr-cors/src/ZfrCors/Mvc/CorsRequestListener.php(83): ZfrCors\Service\CorsService->isCorsRequest(Object(Zend\Http\PhpEnvironment\Request))
#4 [internal function]: ZfrCors\Mvc\CorsRequestListener->onCorsPreflight(Object(Zend\Mvc\MvcEvent))
#5 ./vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 ./vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('route', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 ./vendor/zendframework/zend-mvc/src/Application.php(319): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 ./public/index.php(37): Zend\Mvc\Application->run()
#9 {main}
```

### PR DESCRIPTION
**Pull request by boesing**
fixes #44

### CODE REVIEW

**Comment by amahrt** [comment]
As mentioned in #44 I don't think it's a good idea to set the isCorsRequest to false then. Maybe we should return HTTP 400.

**Comment by bakura10** [comment]
ping @danizord

I think as well we should return 400. After all Cors is a "security" mechanism so if an invalid value is sent, we should rather return an invalid response instead of continuying the whole request flow.

@weierophinney opinion?

**Comment by bakura10** [comment]
To create a response you could maybe use sometihng like that: https://github.com/zf-fr/zfr-cors/blob/master/src/ZfrCors/Mvc/CorsRequestListener.php#L134

You could create a new "InvalidOriginException" exception, throw it in the service, and catch it here https://github.com/zf-fr/zfr-cors/blob/master/src/ZfrCors/Mvc/CorsRequestListener.php#L83 and creating an error response.

**Comment by weierophinney** [comment]
> I think as well we should return 400. After all Cors is a "security" mechanism so if an invalid value is sent, we should rather return an invalid response instead of continuying the whole request flow.
> 
> @weierophinney opinion?

I agree. If the Origin header is missing, you cannot verify that the request is coming from an acceptable location. Most modern browsers will send it, so absence of it typically means somebody is using a tool such as cURL, HTTPie, etc., and missing the header when they craft their request. 400 is a good status in that case.

**Comment by boesing** [comment]
I've added the changes which provide `400 Bad Request` response for invalid `Origin` header.

**Comment by boesing** [comment]
Any ETA here when this probably gets merged? Heading forward to use this fix.

**Comment by bakura10** [comment]
This looks good to me.

**Comment by bakura10** [comment]
I've tagged 1.4.0 :).

**Pull request merged**
