### PR TITLE
DOO-20232 -> Master: Fixed php version

### PR DESCRIPTION
**Pull request by code0dev**

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Couple things needed:

 1. CI pipeline must run, before we consider a merge - for that, we may want to upgrade to github actions, and use https://github.com/laminas/laminas-ci-matrix-action
 2. the specified supported PHP version should be `^7.1 || ~8.0.0 || ~8.1.0`, since `8.2.0` is still unknown, and PHP does not support SemVer
 3. we may need to change all `zendframework/` dependencies to be `laminas/` instead
 4. commit message and PR descriptions need to be adjusted (DOO-20232 means nothing)

**Comment by code0dev** [comment]
Thanks for the comments. I will fix all problems.

**Comment by Blurazzle** [comment]
Is there any update or progress on this pull request?

**Comment by Ocramius** [comment]
No, in fact closing here.

Please open a new PR with running CI and adjusted dependencies.

**Pull request closed without merging**
