### PR TITLE
Method Routes preflight

### PR DESCRIPTION
**Pull request by boesing**
- [x] Failing unit test
- [x] Bugfix

### CODE REVIEW

**Comment by boesing** [comment]
I've added a possible workaround now.

The thing is, that in a `route-not-found` case, the router is being called twice.

1. `CorsRequestListener` (requested with `GET`, but maybe the route with GET does not exist)
2. `RouteListener` (requested with `OPTIONS`)

Maybe, there is a smarter solution? Some suggestions?

**Comment by boesing** [comment]
Depends on #56

**Comment by boesing** [comment]
Fixes #53

**Comment by svycka** [comment]
can we expect this merged and released?

the error is correct php 5.6 does not support callable return type :)
but the question is how it installed `doctrine/instantiator 1.1.0` on php 5.6 when `doctrine/instantiator 1.1.0` requires ^7.1 maybe just travis cache problem or composer? lets hope it's not the case :dagger:

**Comment by boesing** [comment]
I stopped contributing to this project as there is no maintainer anymore. 
I've applied #56 and this to a fork and using it in production for a while now.
Tho, do not expect more releases of this.

**Comment by svycka** [comment]
why no maintainer? and why you closed this?

 ping @Ocramius @Orkin @bakura10

**Comment by Orkin** [comment]
Hi, sorry for that but I have no time for maintain this project right now, but maybe we can think to add someone else to the maintainer team to solve thoses problems ?

As @macnibblet told it, it can be good to fix unit tests before merging this

**Comment by Orkin** [comment]
I think @boesing is better placed because he has made more contributions. What do you think @Ocramius  ?

**Comment by svycka** [comment]
even better if he will agree

**Comment by ddelrio1986** [comment]
@boesing said above that he is no longer contributing to this. Can we get another maintainer added. I'd be willing to help with maintenance.

**Comment by Orkin** [comment]
Ok @svycka I promote you as maintainer 😃

**Pull request closed without merging**
