### PR TITLE
Implemented ability to configure `CorsOptions` by configuring route p…

### LINKED ISSUE #9: Integrate more tightly with the ZF Router
Integrate more tightly with the ZF Router so that CORS can be configured per route instead than globally

### PR DESCRIPTION
**Pull request by boesing**
…arameters without breaking backwarts compatibility

fixes #9

### CODE REVIEW

**Comment by boesing** [comment]
Would you mind merging my feature? Would love to use this in some projects.

**Comment by ddelrio1986** [comment]
I was able to achieve per-route CORS configuration by just using a delegator service factory to override how CorsOptions is built.

**Comment by roypalacios** [comment]
Any plan to release this feature?

**Comment by ddelrio1986** [comment]
@roypalacios first I created a delegator service factory that will alter how \ZfrCors\Options\CorsOptions is built. I registered my delegator in my module configuration like so:

```php
<?php

return [
    'delegators' => [
        'ZfrCors\Options\CorsOptions' => [
            'Ease\Options\CorsOptionsFactory',
        ],
    ],
];
```

Here is the code for my delegator service factory:

```php
<?php
/**
 * Cors Options Factory
 *
 * A delegator factory that will load CORS configuration based on the current route.
 *
 * @package Ease\Options
 * @filesource
 */

namespace Ease\Options;

use Zend\ServiceManager\DelegatorFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use ZfrCors\Options\CorsOptions;

/**
 * Cors Options Factory
 *
 * A delegator factory that will load CORS configuration based on the current route.
 *
 * @package Ease\Options
 */
class CorsOptionsFactory implements DelegatorFactoryInterface
{

    /**
     * Create Deletegator With Name
     *
     * @param ServiceLocatorInterface $serviceLocator
     * @param string $name
     * @param string $requestedName
     * @param callable $callback
     * @return CorsOptions
     */
    public function createDelegatorWithName(ServiceLocatorInterface $serviceLocator, $name, $requestedName, $callback)
    {

        // Get the default CORS configuration
        $applicationConfiguration = $serviceLocator->get('Config');
        $corsConfiguration = $applicationConfiguration['cors']['default'];

        // Get the current route.
        $request = $serviceLocator->get('Request');
        $router = $serviceLocator->get('Router');
        $routeMatch = $router->match($request);
        if ($routeMatch !== null) {
            $currentRoute = $routeMatch->getMatchedRouteName();

            // Get the correct CORS configuration for the current route.
            if (array_key_exists($currentRoute, $applicationConfiguration['cors'])) {
                $corsConfiguration = $applicationConfiguration['cors'][$currentRoute];
            }
        }

        // Get an options object with our settings.
        return new CorsOptions($corsConfiguration);
    }
}
```

Finally, here is an example of a valid configuration file:

```php
return [
    'cors' => [
        'default' => [
            'allowed_origins' => ['*'],
        ],
        'api_attempt' => [
            'allowed_credentials' => true,
            'allowed_methods' => ['POST', 'OPTIONS'],
            'allowed_origins' => [
                'http://s3.amazonaws.com',
                'https://s3.amazonaws.com',
                'http://s3-ap-southeast-2.amazonaws.com',
                'https://s3-ap-southeast-2.amazonaws.com',
                'file://mobile',
            ],
        ],
    ],
];
```

**Comment by roypalacios** [comment]
Thanks for sharing @ddelrio1986, for now I'm enabling CORS on all my endpoints; so basically I'm waiting until this issue is merged and released. But I'm definetely using your method if this is not released.

**Comment by weierophinney** [comment]
Thanks, @boesing. Released with v1.5.0.

**Pull request merged**
